name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      #- name: Lint with flake8
      #run: flake8 --exclude="*.md" simpost tests

      - name: Check formatting with black
        run: black --check simpost tests

      #- name: Type check with mypy
      #  run: mypy simpost tests

      - name: Test with pytest
        run: pytest --cov=simpost tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
